apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend-tests-go-bzzryvas 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures, attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment.   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used tssc-gitops as the grouping
    argocd/app-selector: tssc/gitops=backend-tests-go-bzzryvas
    backstage.io/kubernetes-id: backend-tests-go-bzzryvas 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/backend-tests-go-bzzryvas
    jfrog-artifactory/image-name: backend-tests-go-bzzryvas
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 